#!/bin/sh
# password dialog for Knoppix  Chris Liechti
# based on sshstart by Klaus Knopper
# apr 2003

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin"
export PATH

if [ ! -d /KNOPPIX/etc ] ; then 
	echo -e "FATAL ERROR!\nThis Knoppix script must not be run on a regular system.\nAborting."
	exit 1
fi

TITLE="Set password for user \"knoppix\""

# LANG et al.
[ -f /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n

[ "`id -u`" != "0" ] && exec sudo "$0" "$@"

XDIALOG_HIGH_DIALOG_COMPAT=1
export XDIALOG_HIGH_DIALOG_COMPAT

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#samba password file must be not be a link to the CD
SMBPASS=/etc/samba/smbpasswd
if [ -L $SMBPASS ] ; then
	rm -f $SMBPASS
	cp -a /KNOPPIX$SMBPASS $SMBPASS
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
case "$LANGUAGE" in
	de*) MESSAGE1="Passwort für Benutzer 'knoppix' setzen";
	     MESSAGE2="Wiederhole Passwort";
	     MESSAGE3="Passwörter stimmen nicht überein"; ;;
	*)   MESSAGE1="Set password for user 'knoppix'";
	     MESSAGE2="Retype password";
	     MESSAGE3="Passwords did not match"; ;;
esac

echo ""

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
FORCE=false
echo "$@" | grep force && FORCE=true

#loop while password is not set
while grep -q '^knoppix:\*:' /etc/shadow || grep -q '^knoppix:1000:XXXXX' /etc/samba/smbpasswd || $FORCE ; do
	PASSWORD1=$($DIALOG --stdout --passwordbox "$MESSAGE1" 0 0) || break
	PASSWORD2=$($DIALOG --stdout --passwordbox "$MESSAGE2" 0 0) || break
	if [ "$PASSWORD1" == "$PASSWORD2" ] ; then
		#set system password and samba password
		echo "knoppix:$PASSWORD1" | chpasswd
		echo -e "$PASSWORD1\n$PASSWORD1" | smbpasswd -a knoppix -s
	else
		$DIALOG --msgbox "$MESSAGE3" 0 0
	fi
	#force is only executed once
	FORCE=false
done

exit 0

