#!/bin/sh
# password dialog for Knoppix  Chris Liechti
# based on sshstart by Klaus Knopper
# apr 2003
# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de> for Kanotix, GPL2

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

# override tool behaviour through distro-defaults
FLL_DISTRO_NAME="sidux"
FLL_LIVE_USER="knoppix"
FLL_IMAGE_DIR="KNOPPIX"
FLL_IMAGE_FILE="KNOPPIX"
FLL_IMAGE_LOCATION="$FLL_IMAGE_DIR/$FLL_IMAGE_FILE"
FLL_MOUNTPOINT="/KNOPPIX"

[ -r /etc/default/distro ] && source /etc/default/distro


if [ ! -d ${FLL_MOUNTPOINT}/etc ] ; then 
	echo -e "FATAL ERROR!\nThis ${FLL_DISTRO_NAME} script must not be run on a regular system.\nAborting."
	exit 1
fi

TITLE="Set password for user \"${FLL_LIVE_USER}\""

[ "`id -u`" != "0" ] && exec su-me "$0" "$@"

XDIALOG_HIGH_DIALOG_COMPAT=1
export XDIALOG_HIGH_DIALOG_COMPAT

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"


# samba password file must be not be a link to the CD
SMBPASS=/etc/samba/smbpasswd
if [ -L $SMBPASS ] ; then
	rm -f $SMBPASS
	cp -a ${FLL_MOUNTPOINT}$SMBPASS $SMBPASS
fi

# localisation
case "$LANG" in
	de*) MESSAGE1="Passwort für Benutzer ${FLL_LIVE_USER}' setzen";
	     MESSAGE2="Wiederhole Passwort";
	     MESSAGE3="Passwörter stimmen nicht überein"; ;;
	*)   MESSAGE1="Set password for user '${FLL_LIVE_USER}'";
	     MESSAGE2="Retype password";
	     MESSAGE3="Passwords did not match"; ;;
esac

echo ""

FORCE=false
echo "$@" | grep force && FORCE=true

#loop while password is not set
while grep -q '^${FLL_LIVE_USER}:\*:' /etc/shadow || grep -q '^${FLL_LIVE_USER}:$(getent passwd "$FLL_LIVE_USER" | cut -d\: -f2):XXXXX' /etc/samba/smbpasswd || $FORCE ; do
	PASSWORD1=$($DIALOG --stdout --passwordbox "$MESSAGE1" 0 0) || break
	PASSWORD2=$($DIALOG --stdout --passwordbox "$MESSAGE2" 0 0) || break
	if [ "$PASSWORD1" = "$PASSWORD2" ] ; then
		#set system password and samba password
		echo "${FLL_LIVE_USER}:$PASSWORD1" | chpasswd
		echo -e "$PASSWORD1\n$PASSWORD1" | smbpasswd -a ${FLL_LIVE_USER} -s
	else
		$DIALOG --msgbox "$MESSAGE3" 0 0
	fi
	#force is only executed once
	FORCE=false
done

exit 0

